### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by montage125** [EtherealEngine/etherealengine#7087]
![image](https://user-images.githubusercontent.com/36287216/195771492-52019d59-d400-413a-9eb7-070b5e5455a6.png)

1. It is recommended to fill in the mobile phone number and email address separately for Air Lines 2 to make them clearer.
2. How to use the mobile phone number? Do you want to receive the SMS verification code?

**Comment by barankyle** [comment]
Ethereal Engine has two primary forms of login: OAuth, via the social logins section at the bottom, and magiclink messages via email or SMS. Magiclinks are passwordless messages that get sent to an email address or phone number; they contain a link that, when followed, will log the user in (creating a new user if that email/phone number is not linked to a user already). We have both methods use the same input field since the backend code is mostly identical, but I can see where that might be confusing. There are some revamps of the SMS login on our roadmap, but it may not be addressed for a while.

SMS may also not be working at the moment since some new US laws took effect recently that require much greater vetting of use of SMS for business messaging. The process for getting a review for the SMS number we use for login at app.etherealengine.com/demo.etherealengine.com showed us that wireless providers have several new UI standards they're enforcing that Ethereal Engine currently doesn't have, so it may not be possible for phone magiclinks to get approved until we address them, hence the revamps to it on the roadmap.
