### ISSUE TITLE
[Bug]: Unparenting an object changes its global transform

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#8631]
If you unparent an object in the scene, it will lose the transform that it currently has. We need to be able to unparent an object and have its transform stay as it is, and its local transform updates to keep its position, rotation and scale constant

**Comment by aditya-mitra** [comment]
Hi @dinomut1 
I tried to reproduce this by the below steps:

**object before parenting**

![image](https://github.com/EtherealEngine/etherealengine/assets/55396651/3ed52bc3-9278-453a-93b2-16f531b9f581)

**after parenting and applying rotation**

![image](https://github.com/EtherealEngine/etherealengine/assets/55396651/d4013d1f-5a3d-4733-b005-9733cfe85077)

**after un-parenting the rotation still exists**

![image](https://github.com/EtherealEngine/etherealengine/assets/55396651/9e464777-8886-4294-8f00-bb3fa75ef423)

Can you please tell me if this reproduction of the issue was correct?
