### ISSUE TITLE
[Bug]: URL Clashes for Assets with the Same Name on Deployment

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#8670]
If there are two assets that have the same name on deployment, even if they are in different folders, their URLs in static resources are the same, causing them to clash. 
To reproduce:
In any project on deployment, upload two different assets. Make a folder and put one asset into the folder. Then rename both assets to have the same name. Try placing both of the assets into the scene, then save scene and refresh. Upon refresh, the assets will be the same, as their static resource URLs will be the same.

**Comment by HexaField** [comment]
This might be due to incorrectly constructing hashes

**Comment by barankyle** [comment]
I think this might be due to improper caching, which might be related to #8642. I think what's happening is the following (using images as examples):

FileA.png is uploaded. What gets returned to the file browser is the Cloudfront URL, due to the change I made in 8642.
FileB.png is uploaded. Also returned in the Cloudfront URL.
FileA.png is clicked on, which hits Cloudfront, which now caches FileA.png's contents.
FileA.png is moved to /folder
FileB.png is renamed to FileA.png
When FileB.png is dragged into the editor, it makes a node with the correct URL.
The scene is saved, which causes multiple calls to addAssetToProject. For the former FileB, it's passing e.g. https://resources.etherealengine.com/projects/test/FileA.png, as that is its new name. getFileMetadata is hitting that URL, and getting back the cached metadata about the actual FileA. It calculates the hash from actual FileA's size, sees a match with the actual FileA, and rewrites the URL to point to FileA.png.
Upon reload, the URL is now pointing to /folder/FileA.png.

When the file browser was previously using the S3 URLs, this wasn't a problem, because none of those were cached such that a backend call would get information that wasn't up-to-date, I think.

It seems like there needs to be a smarter way to determine URLs. The problem that 8642 solved poorly was that the projects were being saved with S3 URLs if you were dragging files onto the studio from the file browser; the file browser was returning the S3 URLs because it just piped the listObjects result from S3 directly back to the client, and then when dragging the file into the scene, it was making a node with that URL. But since the S3 URL isn't seen as a self-referential URL to a file that's in the deplyoment, it wouldn't replace that with __$project$__ when saving the scene. If you push that project to GH or download it, then import it into a different deployment, it's still pointing to the original deployment's files because it sees them as external the whole way through.

So, we may have to go back to returning S3 URLs to the file browser (which will likely solve other problems I'm seeing), but when uploading the file to the backend, it somehow needs to be flagged as being an internal file so that it's not written as an S3 URL to the project file.
