### ISSUE TITLE
Thumbnail Handling

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#9512]
- Create a client-side "generateThumbnail" function which takes a GLTF model, image or video, and generates a thumbnail either through rendering or downsampling

- Add logic to File Browser Panel and Assets Panel where, when static resource queries occur, every response object that doesn't have a thumbnail defined is added to a thumbnail generation queue

- Add an extra `thumbnail` column in static-resources table

- Create a feathers service `upload-thumbnail`, which uses a Frankenstein monster combination of the File Browser and Static Resources to upload an image to the `thumbnails` folder of a project and then associate that thumbnail with an asset in the static resources. The service should consist of a single function which accepts a blob, representing the thumbnail image, and a static resource key, which points to the static resource that this thumbnail should be associated with. 
1. The blob is uploaded to the server. The server gleans the target project from where the static resource is. If that project does not have a `thumbnails` folder, create it
2. Save the thumbnail image into the `thumbnails` folder.
3. If the target static resource already has a thumbnail, delete it
4. Associate the static resource with the thumbnail through the `thumbnail` column in the target static resource

- Add a hook onto the deletion of static resources which deletes the associated thumbnail, but only if the thumbnail resides in a project's `thumbnails` folder

**Comment by Rezmason** [comment]
Dev notes

```
Make some kind of Feathers service
	Rerender stuff
		Models: default lighting/camera situation
		Images
		Videos
		128x128

Static resources
	All assets are stored in there
	Every asset any project has are in there
	addendum
		Thumbnail URL
		Handle bookkeeping
		Seems like most of the time people just have a solution where they generate a bunch of JPGs
		Some folder in the backend with a bunch of generated thumbnails
			Periodically updated, deleted/regenerated
				Kinda like a filesystem event
			Separate files

Ask Kyle and some other backend people
	because Dave doesn't know the exact way to render these server side
	On our deployments, we don't have graphics cards
		And there's this special thing we do where on our servers we don't load any textures or anything in-memory
			because there's no GPU
	Seems like we'll have to render on the client and upload to the server
```

**Comment by barankyle** [comment]
Crash course in feathers and the backend in general:

We have a schema file for a service in packages/common/src/schemas/<schema-type>/<service-name>.schema.ts. e.g., For the backend service file-browser-upload, which is located at packages/server-core/src/media/file-browser-upload, its schema file is at packages/common/src/schemas/media/file-browser-upload.ts

The schema contains a few things. At minimum, it contains the path of the service and the allowed methods, conventionally named e.g. fileBrowserUploadPath and fileBrowserUploadMethods. It may also contain schema information if the service accepts and/or returns data. There can be multiple schemas for different methods. Look at something like common/src/schemas/media/static-resources.schema.ts for an example of how the schemas are defined. 

The *Path should be all lowercase, hyphens between words, i.e. `upload-thumbnail`. *Methods is an array of methods that the service supports; anything that is missing will end up returning a method not supported error when called. Options are 'get', 'find', 'create', 'patch', update', and 'remove'. 'get' is to retrieve a single item by ID. 'find' is to search for one or more items by a query. 'create' is a POST, 'patch' is PATCH, update is PUT, and 'remove' is DELETE. 

The rest of the files will be in packages/server-core/src/<schema-type>/<service-name>. A lot of these files can be copy-pasted from an existing service and then changing the names to match the service you're creating.

<service_name>.class.ts mostly exports the interface(s) and service definition so Feathers can run it.
<service-name>.docs.ts is the feathers documentation file, most of them are stubs. It should have any schemas defined for that service and a description.
<service-name>.hooks.ts is where a lot of the magic happens. Hooks are functions that are called before and/or after a service method; their documentation probably explains it better than I could: https://feathersjs.com/api/hooks. For our purposes, the new upload-thumbnail function should have `iff(isProvider('external'), verifyScope('editor', 'write'))` in its before:all array, which will make sure that only users with editor:write scope can use that service.
<service-name>.ts is where the service is run by the app, along with some options. Mostly just copy/paste/modify names here.

If a service has a database table, there will be a folder server-core/src/<schema-type>/<service-name>/migrations. Files in here are is used to create or modify the associated table. Migrations are timestamped in the name based on when the file itself is created, and the timestamp determines the order in which they're run, from oldest to newest timestamp. The timestamp doesn't actually have to be exact, just make sure it's close. With a service like static-resource, the oldest migration will do the heavy lifting of creating the table, while any additional migrations should only need to alter the existing table. Knex applies these migrations, and records which ones have already been run afterwards, so if you make a new migration after a database has already been set up/configured, it will just run the new one.

Migration files have an `up` function and a `down` function. Migrations can actually be reversed; `up` is what's run when applying a migration, and `down` is what's run when reversing it, so `down` should undo whatever `up` does.

See server-core/src/user/user/migrations for an example of a service we have that has multiple migrations. upload-thumbnail shouldn't need any migrations since it won't have a database table of its own, and will just be working with other services that have their own tables. The static-resource service will need an additional migration to add the thumbnail column (or thumbnailUrll and thumbnailKey columns, if we want to store both).

You can test a migration by stopping `npm run dev` and then running `npm run prepare-database`. This will attempt to apply any migrations that haven't been run already. `npm run dev-reinit-db` will wipe the whole database, so without any record of migrations being applied, they will then all be applied.

Inside the the <service-type> folder, there's a file called `services.ts`, e.g. server-core/src/media/services.ts. You need to import any new services you make into the service.ts file for the type folder it's in and then export it in the export default array in that service.ts file, otherwise Feathers doesn't configure it when the API server boots and the service won't be recognized.

**Comment by Rezmason** [comment]
Finally! PR: https://github.com/EtherealEngine/etherealengine/pull/9672

**Comment by Rezmason** [comment]
Note: a moved/renamed/removed static resource should cause its thumbnail to be moved/renamed/removed. That is considered outside the scope of this ticket.

**Comment by Rezmason** [comment]
Note: https://github.com/EtherealEngine/etherealengine/tree/9512-generate-all-file-thumbnails contains the button that will kick off thumbnail generation for every eligible static resource in an open project.

It should be used to roll out thumbnails for our projects, but should not go into `dev`.

**Comment by Rezmason** [comment]
![image](https://github.com/EtherealEngine/etherealengine/assets/1041555/414e22af-c796-45cf-b9e3-55c873d1b9b5)

**Comment by HexaField** [comment]
> ![image](https://private-user-images.githubusercontent.com/1041555/314251218-414e22af-c796-45cf-b9e3-55c873d1b9b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODc0MTMsIm5iZiI6MTcxMDg4NzExMywicGF0aCI6Ii8xMDQxNTU1LzMxNDI1MTIxOC00MTRlMjJhZi1jNzk2LTQ1Y2YtYjllMy01NWM4NzNkMWI5YjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMjIyNTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWZhYWNjYmExZDBiY2M5Zjk0NTBkM2UzNDdhNTM3N2I4Y2M2YzY3YmRhN2VjMzFhNmUyN2I4MGVmYjE3Y2MxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pwX3XGk-gDbfV7o1SzYUoMzJxnCfoa20HtcbHUEK9fo)

let's move this to the file browser UI under the settings cog instead of the studio toolbar, with an option to generate per-file

**Comment by Rezmason** [comment]
@HexaField Can you clarify what you mean by an "option to generate per-file"?

**Comment by Rezmason** [comment]
Moved the auto-generate button into the menu beneath the gear in the file browser UI

**Comment by Rezmason** [comment]
https://github.com/EtherealEngine/etherealengine/pull/9672 has been merged into `dev`
